version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/docs'
    schedule:
      interval: daily
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/testbed'
    schedule:
      interval: daily
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
