version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          commmand: yarn build
      - run:
          name: release
          command: yarn run semantic-release || true
