version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: release
          command: yarn semantic-release || true
